apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: goserver
  newName: vinicamposdev/gitopsfc
  newTag: 5ac780985b23fa79343141e0e5fc32f4714c7e5f
